# Generated by Django 5.1.2 on 2025-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breadth',
            field=models.FloatField(default=1.0, help_text='Breadth in cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=1, help_text='Height in cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=1.0, help_text='Length in cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight in kilograms'),
            preserve_default=False,
        ),
    ]
