# Generated by Django 5.1.2 on 2025-05-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_breadth_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
