# Generated by Django 4.1.5 on 2024-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_review_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="image",
        ),
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="review",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="review_media/"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
