# Generated by Django 5.1.2 on 2025-06-14 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_awb_code_order_shipment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_code', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_courier', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('main_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='accounts.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
