# Generated by Django 5.1.2 on 2025-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shiprocket_pickup_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
