# Generated by Django 5.1.2 on 2025-06-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_shiprocket_pickup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shiprocket_pickup_name',
        ),
    ]
