# Generated by Django 5.1.2 on 2025-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_delivery_date_order_delivery_status_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='shipment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
