# Generated by Django 5.1.2 on 2025-06-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_suborder_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='shipment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='suborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.suborder'),
        ),
    ]
