# Generated by Django 5.1.2 on 2025-06-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_suborder_shipment_status_order_suborder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='suborder',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='suborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.suborder'),
        ),
    ]
