# Generated by Django 5.1.2 on 2025-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_order_suborder_orderitem_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
