# Generated by Django 5.1.2 on 2025-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_suborder_platform_fee_suborder_seller_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='is_return_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='is_return_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='is_return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
