# Generated by Django 5.1.2 on 2025-07-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_suborder_is_refunded_suborder_is_return_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
