"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from django.core.mail.backends.smtp import EmailBackend

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8(m0c7l$arcolnk_@g_!!snqs44zy*kw$z94t#g9(36^9jamwo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.124', 'localhost', '0.0.0.0','127.0.0.1','http://192.168.1.111:8000','192.168.1.111', '192.168.1.37',
]


# Application definition

INSTALLED_APPS = [
 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'appname',
    'base',
    'allauth', #from here
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', 
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'django.contrib.sites',
      # Required by Django Allauth
  
  
]

AUTHENTICATION_BACKENDS =[
    'accounts.backends.EmailBackend',
    'allauth.account.auth_backends.AuthenticationBackend',  # Correct spelling here # google
    'django.contrib.auth.backends.ModelBackend',  # For Django's default authentication
    
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.CartMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'appname.middleware.SaveCartOnLogoutMiddleware',
]


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appname.context_processors.cart_count_processor',
            ],
        },
    },
]
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '182188989997-patnmavcel670qqni4ib1bv0ifi9c53h.apps.googleusercontent.com',
            'secret': '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',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
    },
    'facebook': {
        'APP': {
            'client_id': '1202659857643739',
            'secret': '220f187742ab76d44706051d31f610dc',
        },
    }
}


# SOCIAL_AUTH_FACEBOOK_KEY ="1202659857643739"
# SOCIAL_AUTH_FACEBOOK_SECRET="220f187742ab76d44706051d31f610dc"
WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / "media"


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    
] 


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "kavleensaluja22@gmail.com"
EMAIL_HOST_PASSWORD = "njth yuiq zmjo rrqb"

EMAIL_USE_SSL = False

# SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True  
ACCOUNT_AUTHENTICATION_METHOD = "email"  
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Ensure verification is required
SOCIALACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Enforce email verification for social logins
SOCIALACCOUNT_AUTO_SIGNUP = False  # Prevent automatic signup before email verification

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_SECONDS = 600  # Token expires in 10 minutes
ACCOUNT_CONFIRM_EMAIL_ON_GET = True 
# SOCIALACCOUNT_ADAPTER = "appname.adapters.MySocialAccountAdapter"

# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # or "optional"
# ACCOUNT_AUTHENTICATION_METHOD = "email"

ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_AUTO_SIGNUP = False  # Prevent auto-signup without email confirmation

EMAIL_USE_HTML = True

SITE_ID = 2

# settings.py
LOGIN_URL = '/user_login'  # Redirect to this URL if the user is not logged in

RAZORPAY_KEY_ID = "rzp_test_4t8nCdN7uI0xEP"
RAZORPAY_KEY_SECRET = "6PWff6o8IE8dtouN2DMfBquc"

ACCOUNT_SIGNUP_REDIRECT_URL = '/'  # Redirect home after email confirmation
ACCOUNT_LOGIN_REDIRECT_URL = '/'  # Ensure login also redirects home
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/'  # Redirect for logged-out users
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'

ACCOUNT_ADAPTER = "accounts.adapters.MyAccountAdapter"

DEFAULT_FROM_EMAIL = 'kavleensaluja22@gmail.com'  # or your verified domain email


DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

SHIPROCKET_EMAIL="work.kavleen@gmail.com"
SHIPROCKET_PASSWORD="x@9yRW1Qw4TF#p$P"
