# Generated by Django 5.1.2 on 2025-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
