# Generated by Django 5.1.2 on 2025-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_profile_kyc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coustmer_pincode',
            field=models.IntegerField(default=134203),
            preserve_default=False,
        ),
    ]
