# Generated by Django 5.1.2 on 2025-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_profile_city_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shiprocket_pickup_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
