# Generated by Django 5.1.2 on 2025-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_profile_shiprocket_pickup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shiprocket_pickup_name',
            new_name='custom_pickup_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coustmer_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
